name: Run PHP tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  run-test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        php: [7.4, 8.0, 8.1, 8.2, 8.3]
        # dependency-version: [prefer-lowest, prefer-stable]
        dependency-version: [prefer-stable]

    name: PHP${{ matrix.php }}_${{ matrix.dependency-version }}

    steps:
    - uses: actions/checkout@v3

    - uses: shivammathur/setup-php@v2
      with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

    - name: Install dependencies
      run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

    - name: Check coding style
      run: vendor/bin/phpcs -s --standard=phpcs.ruleset.xml .

    - name: Execute tests
      run: vendor/bin/phpunit

    # TODO: add codecoverage // vendor/bin/phpunit --coverage-clover logs/clover.xml
